name: Trunk Code Quality
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: read-all

jobs:
  test:
    name: Run and Upload Tests
    runs-on: ubuntu-latest
    steps:
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
